### ISSUE TITLE
Add Retry to uncatched_errors to support embedded formgen forms

### ISSUE THREAD

**Issue by frisi** [plone/plone.app.viewletmanager#5]
can we add ``ZPublisher.Publish.Retry`` to the list of `_uncatched_errors` in
https://github.com/plone/plone.app.viewletmanager/blob/2.0.6/plone/app/viewletmanager/manager.py#L30 directly?

this would make embedded ploneformgenforms in viewlets  work again.
see https://github.com/smcmahon/Products.PloneFormGen/issues/130 for more details.

adding it here might help other addons using the same technique w/o a patch.

**Comment by jensens** [comment]
merged #9
